### ISSUE TITLE
Dynamic urls with a function lambda

### ISSUE THREAD

**Issue by AAA3A-AAA3A** [h-janes/flask-sitemapper#12]
Hello,

First of all, thank you for this functional Flask extension.
Let me explain my problem. I have a `/creators` page that takes a `creator` username as a dynamic parameter. Your extension supports dynamic parameters, but only once at web server startup. That's why you should allow lambda functions to retrieve an updated list of parameters each time `/sitemap.xml` is used.
What's more, you can't use databases without an application context.

Thanks in advance,
Have a nice day and happy holidays!
AAA3A

**Comment by TheLostProgrammer** [comment]
Yeah, I have the same problem and would love if something was added to fix this.

**Comment by h-janes** [comment]
sorry for the long wait - I am working on adding this functionality now.

**Comment by h-janes** [comment]
I have made changes to allow the `url_variables` parameter to be either a `dict` (as previously) or a `Callable` which returns a dictionary of the same format.

If a `dict` is provided, it will work the same way as before.

If a `Callable` is provided, this will be run upon every call to `sitemapper.generate()` and the returned `dict` will be used. They will always be run within the app context.  However, to use this functionality, you must disable xml caching when creating the sitemapper instance, like this: `sitemapper=Sitemapper(cache_xml=False)`

Example:
```python
from flask import Flask
from flask_sitemapper import Sitemapper

def generate_user_ids():
    return {"user_id": [4, 5, 6]}

sitemapper = Sitemapper(cache_xml=False)

app = Flask(__name__)
sitemapper.init_app(app)

@sitemapper.include(url_variables=generate_user_ids)
@app.route("/user/<int:user_id>")
def r_user(user_id):
    return f"<h1>User #{user_id}</h1>"

@app.route("/sitemap.xml")
def r_sitemap():
    return sitemapper.generate()

app.run("127.0.0.1", 8000)
```

I have not released this on PyPi yet as I want to do more testing first, but I have made a commit on the main branch. If you're still interested after 3 months (my bad), feel free to clone the repo and give it a try and let me know if it solves your problem. Otherwise I will continue testing myself and publish as v1.8.0 when satisfied.

The changes are in url.py and sitemapper.py

Thanks for opening the issue

**Comment by TheLostProgrammer** [comment]
Hey,

Thank you so much for putting in the time to add that feature. I greatly appreciate it. 

During my short time using it, I found that it kept adding the `dynamic_endpoints` each time I refreshed the sitemap.xml even though they were already there. I had a look at the source code and found it was because they are being appended to the `self.urls` each time. This isn't reset at all which results in the `dynamic_endpoint.urls` being left in the `self.urls`. Then, when you refresh sitemap.xml, the `dynamic_endpoint.urls` are added again to that list.

To fix this, in `sitemapper.xml` in the function `generate`, I added a new variable named`dynamic_endpoint_urls` to append the `dynamic_endpoint.urls` to.
```python
# get all urls for the sitemap
urls = self.urls
dynamic_endpoint_urls = []
for dynamic_endpoint in self.dynamic_endpoints:
    dynamic_endpoint_urls += dynamic_endpoint.urls

# create the final xml document
template = Environment(loader=BaseLoader).from_string(self.template)
xml = template.render(urls=urls + dynamic_endpoint_urls)
```

I then added `dynamic_endpoint_urls` to the `urls` when rendering the template. Each time the `generate` method is called, the list `dynamic_endpoint_urls` will be empty and the `dynamic_endpoint.urls` will be added as per usual. This has fixed the problem that I had and I just wanted to let you know about it so you are aware of the problem.

**Comment by h-janes** [comment]
oops! thanks so much for testing, should be fixed now.
I have also added a test for this in `tests/test_dynamic_route_with_generator_function.py`

**Comment by h-janes** [comment]
didn't mean to close this issue, must have clicked by accident

**Comment by h-janes** [comment]
I have now removed the need to specify `cache_xml=False`. Caching will be enabled by default, however if a `Callable` is provided as the value for `url_variables` it will be disabled automatically.

**Comment by TheLostProgrammer** [comment]
That seems to work perfectly. Nice additions with the `cache_xml`. It's good to have that dynamically changed based on what is passed as the `url_variables`.

Do you have a way to combine two Sitemapper instances? I have a Sitemapper instance in my `auth.py` and another in my `views.py` which I want to merge as a single xml.

**Comment by h-janes** [comment]
Thanks for the feedback. I have answered the question about combining sitemappers in #17

**Comment by h-janes** [comment]
I have finished testing these changes and they are now included in release 1.8.0 on PyPi.

**Comment by AAA3A-AAA3A** [comment]
Thank you very much for adding this functionnality!

**Comment by atao** [comment]
Hello @h-janes 
I've written a new sitemap example with dynamic urls using random data rather than a set list.
If you want to integrate it in the doc.
Thanks for your module, it's really useful.
I can create a pull request if that's more convenient.

```python
"""
This script sets up a Flask web application with a sitemap generator.
The application includes the following routes:
- `/user/<int:user_id>`: Displays an HTML header for a user with the given user ID.
- `/sitemap.xml` and `/`: Generates and returns a sitemap.
Functions:
- generate_user_ids(): Generates a dictionary containing a list of 5 random user IDs.
- r_user(user_id): Generates an HTML header for a user.
- r_sitemap(): Generates and returns a sitemap.
Modules:
- random: Provides functions to generate random numbers.
- flask: A micro web framework for Python.
- flask_sitemapper: A Flask extension for generating sitemaps.
Classes:
- Sitemapper: A class from the `flask_sitemapper` module used to generate sitemaps.
Attributes:
- sitemapper: An instance of the `Sitemapper` class.
- app: An instance of the `Flask` class.
"""

import random

from flask import Flask
from flask_sitemapper import Sitemapper


def generate_user_ids():
    """
    Generates a dictionary containing a list of 5 random user IDs.

    The function generates a list of 5 random integers between 1 and 10 (inclusive)
    and returns a dictionary with the key 'user_id' and the list of random integers as the value.

    Returns:
        dict: A dictionary with a single key 'user_id' and a list of 5 random integers as the value.
    """
    random_integers = [random.randint(1, 10) for _ in range(5)]
    print(random_integers)
    return {"user_id": random_integers}

sitemapper = Sitemapper()

app = Flask(__name__)
sitemapper.init_app(app)

@sitemapper.include(url_variables=generate_user_ids)
@app.route("/user/<int:user_id>")
def r_user(user_id):
    """
    Generate an HTML header for a user.

    Args:
        user_id (int): The ID of the user.

    Returns:
        str: An HTML string containing the user ID in an <h1> tag.
    """
    return f"<h1>User #{user_id}</h1>"

@app.route("/sitemap.xml")
@app.route("/")
def r_sitemap():
    """
    Generates and returns a sitemap.

    This function calls the `generate` method from the `sitemapper` module
    to create a sitemap.

    Returns:
        object: The generated sitemap.
    """
    return sitemapper.generate()

app.run("127.0.0.1", 8000)
```

**Comment by atao** [comment]
Great job ! Many thanks !
