### ISSUE TITLE
This XML file does not appear to have any style information associated with it.

### ISSUE THREAD

**Issue by KikeVen** [h-janes/flask-sitemapper#22]
I implemented the library according to the instructions but am getting the following message and returning XML partial.

"This XML file does not appear to have any style information associated with it. The document tree is shown below."

```xml
<urlset>
<url>
<loc>https://127.0.0.1:5000/</loc>
<lastmod>2024-07-18</lastmod>
</url>
</urlset>
```

Any assistance would be greatly appreciated.

Thank you

**Comment by h-janes** [comment]
Hi, thanks for opening the issue.

### The message you are seeing
This is a message from your browser telling you that the sitemap does not include styles. This is the expected behaviour for this extension in most browsers.

Generally, sitemaps do not include styles as they are designed to be primarily machine readable (by web crawlers). For example, when I view Google's sitemap - https://www.google.com/sitemap.xml - I see the same message in my browser (safari). 

I am definitely not an expert in XML, but as far as I understand, styles can be included in the XML document similar to how CSS can be included in a HTML document. XML is rarely used for user-facing pages so it is uncommon to include styles.

This extension does not include styles for the following reasons:
- Styles increase file size, decreasing download speeds
- Styles are not standard for sitemaps and could possibly confuse some crawlers
- Styles in sitemaps serve only to improve human-readability while sitemaps are designed to be machine-readable.

### The missing XML tags
The missing XML header tag and urlset attributes are likely being served, however they are not rendering directly in your browser window due to your browser's default styles and XML rendering protocol. If you view the page source or inspect element, they should appear. If they don't, let me know.

Overall it seems like your sitemap is working normally from the information you have provided, but please let me know if I have misunderstood. XML is weird. Thanks for using the extension :)

**Comment by KikeVen** [comment]
Thank you for the quick response, I thought the "style information" had something to do with the missing XML tags. I'll reinstall it and view the page source.

Thank you again

**Comment by KikeVen** [comment]
Ok, that was it:

```xml
<?xml version="1.0" encoding="utf-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://127.0.0.1:5000/</loc>
    <lastmod>2024-02-15</lastmod>
  </url>
  <url>
    <loc>https://127.0.0.1:5000/services</loc>
    <lastmod>2024-02-15</lastmod>
  </url>
  <url>
    <loc>https://127.0.0.1:5000/about</loc>
    <lastmod>2024-02-15</lastmod>
  </url>
</urlset>
```

It isn't clear from the documentation if the file needs to be saved in the root, or will the bot automatically look at the site `URL/sitemap.xml`. I set the `generate()` method to `gzip=True` thinking it would save a file to the root directory. 

maybe this is outside of the scope of this library.

Thank you again

~e

**Comment by h-janes** [comment]
Hi, I am glad that sorted it out. Web crawlers will always look for the sitemap at `https://YOUR_DOMAIN/sitemap.xml` by default.
You can change this by writing `Sitemap: https://ANOTHER_URL` at the bottom of your robots.txt file (not recommended as not all bots will look here).

The sitemap does not need to be saved as a file, and flask does not serve files from the root directory by default. As long as you have a route returning `sitemapper.generate()` it will work. The extension will cache the sitemap in memory automatically if possible.

Using GZIP sends a compressed version of the document to the browser. To check that it is working, visit the sitemap URL and inspect the response headers. You should see `Content-Encoding: gzip` among them if you have specified `gzip=True`.
